/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eindexklijent;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Joxyy
 */
@SuppressWarnings("serial")
public class EindexKlijent extends javax.swing.JFrame {

    /**
     * Creates new form EindexKlijent
     */
    private Socket socket;
    private BufferedReader br;
    private PrintWriter pw;
    private PrijemSaServera rmfs;

    public JComboBox<String> getCbKat() {
        return cbKat;
    }

    public JComboBox<String> getCbPredmetiStud() {
        return cbPredmetiStud;
    }

    public JComboBox<String> getCbStudenti2() {
        return cbStudenti2;
    }

    public void setCbKat(JComboBox<String> cbKat) {
        this.cbKat = cbKat;
    }

    public void setCbPredmetiStud(JComboBox<String> cbPredmetiStud) {
        this.cbPredmetiStud = cbPredmetiStud;
    }

    public void setCbStudenti2(JComboBox<String> cbStudenti2) {
        this.cbStudenti2 = cbStudenti2;
    }

    public void setCbPredmetiStud2(JComboBox<String> cbPredmetiStud2) {
        this.cbPredmetiStud2 = cbPredmetiStud2;
    }

    public JComboBox<String> getCbPredmetiStud2() {
        return cbPredmetiStud2;
    }
    
    

    public Socket getSocket() {
        return socket;
    }

    public BufferedReader getBr() {
        return br;
    }

    public PrintWriter getPw() {
        return pw;
    }

    public PrijemSaServera getRmfs() {
        return rmfs;
    }

    public JButton getBtnKonekcija() {
        return btnKonekcija;
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    public void setBr(BufferedReader br) {
        this.br = br;
    }

    public void setPw(PrintWriter pw) {
        this.pw = pw;
    }

    public void setRmfs(PrijemSaServera rmfs) {
        this.rmfs = rmfs;
    }

    public void setBtnKonekcija(JButton btnKonekcija) {
        this.btnKonekcija = btnKonekcija;
    }

    public JComboBox<String> getCbPredmeti() {
        return cbPredmeti;
    }

    public JComboBox<String> getCbPredmeti2() {
        return cbPredmeti2;
    }

    public JComboBox<String> getCbStudenti() {
        return cbStudenti;
    }

    public void setCbPredmeti(JComboBox<String> cbPredmeti) {
        this.cbPredmeti = cbPredmeti;
    }

    public void setCbPredmeti2(JComboBox<String> cbPredmeti2) {
        this.cbPredmeti2 = cbPredmeti2;
    }

    public void setCbStudenti(JComboBox<String> cbStudenti) {
        this.cbStudenti = cbStudenti;
    }
    
    
    
    public EindexKlijent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        taPodaciOStudentu1 = new javax.swing.JTextArea();
        pLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnKonekcija = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        lKonekcija = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        pfPass = new javax.swing.JPasswordField();
        lProveriLogin = new javax.swing.JLabel();
        pAdmin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnStud = new javax.swing.JButton();
        btnDodAdmina = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfIme = new javax.swing.JTextField();
        tfPrezime = new javax.swing.JTextField();
        tfIndex = new javax.swing.JTextField();
        tfJmbg = new javax.swing.JTextField();
        tfNazivPredmeta = new javax.swing.JTextField();
        btnDodPredmet = new javax.swing.JButton();
        cbStudenti2 = new javax.swing.JComboBox<>();
        cbKat = new javax.swing.JComboBox<>();
        lOcena = new javax.swing.JLabel();
        lStudent = new javax.swing.JLabel();
        tfOcena = new javax.swing.JTextField();
        btnKat = new javax.swing.JButton();
        btnDodNaPredmet = new javax.swing.JButton();
        cbStudenti = new javax.swing.JComboBox<>();
        cbPredmeti2 = new javax.swing.JComboBox<>();
        cbPredmeti = new javax.swing.JComboBox<>();
        tfImeKat = new javax.swing.JTextField();
        tfAdminUsername = new javax.swing.JTextField();
        tfAdminPass = new javax.swing.JTextField();
        tfNewUsername = new javax.swing.JTextField();
        tfNewPassword = new javax.swing.JTextField();
        tfMaxBodovi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lProveriBodove = new javax.swing.JLabel();
        cbPredmetiStud = new javax.swing.JComboBox<>();
        pStudent = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPodaciOStudentu = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cbPredmetiStud2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        taPodaciOStudentu22 = new javax.swing.JTextArea();

        taPodaciOStudentu1.setColumns(20);
        taPodaciOStudentu1.setRows(5);
        jScrollPane3.setViewportView(taPodaciOStudentu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN PAGE");
        jLabel1.setToolTipText("");

        jLabel2.setText("Korisnicko ime:");

        jLabel3.setText("Lozinka:");

        btnKonekcija.setBackground(new java.awt.Color(153, 255, 255));
        btnKonekcija.setText("KONEKTUJ SE");
        btnKonekcija.setToolTipText("");
        btnKonekcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonekcijaActionPerformed(evt);
            }
        });

        tfUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfUsername.setText("unesite korisnicko ime");
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        lKonekcija.setText("niste povezani sa serverom");

        btnEnter.setBackground(new java.awt.Color(0, 255, 51));
        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        pfPass.setToolTipText("");

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(pfPass)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addComponent(btnKonekcija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lProveriLogin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnter)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lKonekcija, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pLoginLayout.createSequentialGroup()
                            .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                            .addComponent(lProveriLogin)))
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnKonekcija, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lKonekcija)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("ADMIN");

        btnStud.setBackground(new java.awt.Color(153, 255, 153));
        btnStud.setText("Dodaj studenta");
        btnStud.setToolTipText("");
        btnStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudActionPerformed(evt);
            }
        });

        btnDodAdmina.setBackground(new java.awt.Color(153, 255, 153));
        btnDodAdmina.setText("Dodaj Admina");
        btnDodAdmina.setActionCommand("Dodaj admina");
        btnDodAdmina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodAdminaActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setText("Upis ocene");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tfIme.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfIme.setText("ime");
        tfIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImeActionPerformed(evt);
            }
        });

        tfPrezime.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfPrezime.setText("prezime");

        tfIndex.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfIndex.setText("index");

        tfJmbg.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfJmbg.setText("jmbg");
        tfJmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJmbgActionPerformed(evt);
            }
        });

        tfNazivPredmeta.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfNazivPredmeta.setText("naziv predmeta");

        btnDodPredmet.setBackground(new java.awt.Color(153, 255, 153));
        btnDodPredmet.setText("Dodaj predmet");
        btnDodPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodPredmetActionPerformed(evt);
            }
        });

        cbStudenti2.setName(""); // NOI18N
        cbStudenti2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbStudenti2ComponentShown(evt);
            }
        });
        cbStudenti2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStudenti2ActionPerformed(evt);
            }
        });

        cbKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKatActionPerformed(evt);
            }
        });

        tfOcena.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfOcena.setText("ocena");
        tfOcena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOcenaActionPerformed(evt);
            }
        });

        btnKat.setBackground(new java.awt.Color(153, 255, 153));
        btnKat.setText("Dodaj kategoriju");
        btnKat.setActionCommand("");
        btnKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKatActionPerformed(evt);
            }
        });

        btnDodNaPredmet.setBackground(new java.awt.Color(153, 255, 153));
        btnDodNaPredmet.setText("Dodaj na predmet");
        btnDodNaPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodNaPredmetActionPerformed(evt);
            }
        });

        cbStudenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStudentiActionPerformed(evt);
            }
        });

        cbPredmeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPredmetiActionPerformed(evt);
            }
        });

        tfImeKat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfImeKat.setText("naziv");

        tfAdminUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfAdminUsername.setText("Korisnicko ime");

        tfAdminPass.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfAdminPass.setText("Lozinka");
        tfAdminPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdminPassActionPerformed(evt);
            }
        });

        tfNewUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfNewUsername.setText("username");
        tfNewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNewUsernameActionPerformed(evt);
            }
        });

        tfNewPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfNewPassword.setText("pass");
        tfNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNewPasswordActionPerformed(evt);
            }
        });

        tfMaxBodovi.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfMaxBodovi.setText("maxBodovi");

        jLabel7.setText("potrebno je upisati kategorije i max bodove sa separatorom \" \"");

        jLabel8.setText(" (kat1 kat2 kat3 i bod1 bod2 bod3)");

        lProveriBodove.setForeground(new java.awt.Color(255, 0, 0));
        lProveriBodove.setText("UNESITE 100 bodova zbirno");

        cbPredmetiStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPredmetiStudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAdminLayout = new javax.swing.GroupLayout(pAdmin);
        pAdmin.setLayout(pAdminLayout);
        pAdminLayout.setHorizontalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAdminLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pAdminLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAdminLayout.createSequentialGroup()
                        .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pAdminLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAdminLayout.createSequentialGroup()
                                        .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfNewPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNewUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(pAdminLayout.createSequentialGroup()
                                        .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfIndex, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPrezime, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfIme, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lOcena)
                                            .addGroup(pAdminLayout.createSequentialGroup()
                                                .addComponent(cbKat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfOcena, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbStudenti2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(cbPredmetiStud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(pAdminLayout.createSequentialGroup()
                                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnStud)
                                    .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lStudent)
                                        .addComponent(tfJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(11, 11, 11))
                    .addGroup(pAdminLayout.createSequentialGroup()
                        .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAdminLayout.createSequentialGroup()
                                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDodAdmina, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDodNaPredmet, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(cbStudenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPredmeti2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAdminLayout.createSequentialGroup()
                                    .addComponent(btnDodPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfNazivPredmeta))
                                .addGroup(pAdminLayout.createSequentialGroup()
                                    .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(pAdminLayout.createSequentialGroup()
                                            .addComponent(btnKat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfImeKat, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfMaxBodovi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pAdminLayout.createSequentialGroup()
                                    .addComponent(lProveriBodove)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8))))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        pAdminLayout.setVerticalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAdminLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStud)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStudenti2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPredmetiStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOcena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(tfJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lStudent)
                .addGap(33, 33, 33)
                .addComponent(tfNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodPredmet)
                    .addComponent(tfNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKat)
                    .addComponent(cbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfImeKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfMaxBodovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProveriBodove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodNaPredmet)
                    .addComponent(cbStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPredmeti2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodAdmina)
                    .addComponent(tfAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setText("STUDENT");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Podaci o studentu:");
        jLabel5.setToolTipText("");

        taPodaciOStudentu.setColumns(20);
        taPodaciOStudentu.setRows(5);
        jScrollPane1.setViewportView(taPodaciOStudentu);

        jLabel4.setText("Predmeti koje student slusa");

        cbPredmetiStud2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPredmetiStud2ActionPerformed(evt);
            }
        });

        taPodaciOStudentu22.setColumns(20);
        taPodaciOStudentu22.setRows(5);
        jScrollPane4.setViewportView(taPodaciOStudentu22);

        javax.swing.GroupLayout pStudentLayout = new javax.swing.GroupLayout(pStudent);
        pStudent.setLayout(pStudentLayout);
        pStudentLayout.setHorizontalGroup(
            pStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(pStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPredmetiStud2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pStudentLayout.setVerticalGroup(
            pStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStudentLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbPredmetiStud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)))
                .addComponent(pAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void btnKonekcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonekcijaActionPerformed
        // TODO add your handling code here:
        try {
            //Kreiraj novi socket (ako nije localhost, treba promeniti IP adresu)
            this.socket = new Socket("127.0.0.1", 6001);
            //napravi BufferedReader i PrintWriter kako bi slao i primao poruke
            this.br = new BufferedReader(new InputStreamReader(this.socket.getInputStream()));
            this.pw = new PrintWriter(new OutputStreamWriter(this.socket.getOutputStream()), true);
            //za prijem poruka od servera (stizace asinhrono) koristi poseban thread
            //da bismo u novom thread-u mogli da menjamo sadrzaj komponenti (npr Combo Box-a)
            //konstruktoru novog thread-a se prosledjuje this
            this.rmfs = new PrijemSaServera(this);
            Thread thr = new Thread(rmfs);
            thr.start();
            lKonekcija.setText("Povezani ste sa serverom");

        } catch (IOException ex) {
            Logger.getLogger(EindexKlijent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKonekcijaActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        if (!(this.tfUsername.getText().equals(""))&& !(this.pfPass.getText().equals(""))) {
            this.pw.println(tfUsername.getText()+ ":"+ this.pfPass.getText());
    	}

    }//GEN-LAST:event_btnEnterActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tfJmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJmbgActionPerformed

    private void btnKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatActionPerformed
        // TODO add your handling code here:
        if (!(this.tfImeKat.getText().equals(""))&& !(this.tfMaxBodovi.getText().equals(""))&&!(this.cbPredmeti.getSelectedItem().equals(""))) {

            String unos1 = this.tfImeKat.getText();
            String [] tokens1 = unos1.split(" ");
            
            int suma = 0;
            String unos2 = this.tfMaxBodovi.getText();
            String [] tokens2 = unos2.split(" ");
            String regexPattern = "^(?:[0-9]*{1,2}|100)$";
            
            if (tokens2.length==tokens1.length){
                for (String t : tokens2){
                    if(t.matches(regexPattern)) suma+=Integer.parseInt(t);
                    else this.lProveriBodove.setText("Nisu uneti brojevi na svim mestima");
                }
                if(suma==100) {
                    this.pw.println("novaKat:"+this.cbPredmeti.getSelectedItem()+ ":"+unos1+ ":"+ unos2);
                    this.lProveriBodove.setText("Unos OK");
                }else this.lProveriBodove.setText("Suma unetih bodova nije 100");
            }
            else this.lProveriBodove.setText("Nije unet jednak broj kategorija i bodova");
    	}
    }//GEN-LAST:event_btnKatActionPerformed

    private void btnStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudActionPerformed
        // TODO add your handling code here:
        if (!(this.tfIme.getText().equals(""))&& !(this.tfPrezime.getText().equals(""))) {
            
        String provera= this.tfIndex.getText();           
        String regexPattern = "^[eE][1-3][1-9][0-9]*{0,2}[-/]20(?:[01][0-9]|2[0-3])$";
        if(provera.matches(regexPattern)){
            regexPattern = "^\\d{13}$";
            provera=this.tfJmbg.getText();
            if(provera.matches(regexPattern)){
                String datum = provera.substring(0,2);
                int d = Integer.parseInt(datum);
                String mesec = provera.substring(2,4);
                int m = Integer.parseInt(mesec);
                String godina = provera.substring(4,7);
                int g = Integer.parseInt(godina);
                boolean notRead=true;
                if(d<=31 && m<=12 && (g<5 || g>970)){
                    if(d==31){
                        regexPattern="^(?:0[13578]|1[012])$";
                        if(mesec.matches(regexPattern)) notRead=false;
                        else lStudent.setText("upisani mesec nema 31 dan"); 
                    }else if(d==30){
                        if(mesec.equals("02")) lStudent.setText("upisani mesec nema 30 dana");
                        else notRead=false;
                    }else if(d==29 && mesec.equals("02")){
                        if(g%4==0) notRead=false;
                        else lStudent.setText("Uneta godina nije prestupna");   
                    }else notRead=false;
                }
                if(!notRead) this.pw.println("student:" + tfIme.getText()+ ":"+ this.tfPrezime.getText()+ ":"+ this.tfIndex.getText()+ ":"+ this.tfJmbg.getText()+ ":"+ this.tfNewUsername.getText()+ ":"+ this.tfNewPassword.getText());;
            }else lStudent.setText("Neispravan unos JMBG-a");
    
            }else lStudent.setText("Neispravan broj indexa");
        
            
    	}
    }//GEN-LAST:event_btnStudActionPerformed

    private void tfNewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNewUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNewUsernameActionPerformed

    private void tfNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNewPasswordActionPerformed

    private void btnDodPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodPredmetActionPerformed
        // TODO add your handling code here:
        if (!(this.tfNazivPredmeta.getText().equals(""))) {
            this.pw.println("noviPredmet:"+tfNazivPredmeta.getText());
    	}
    }//GEN-LAST:event_btnDodPredmetActionPerformed

    private void tfImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfImeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pAdmin.setVisible(false);
        pStudent.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void tfAdminPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdminPassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfAdminPassActionPerformed

    private void btnDodAdminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodAdminaActionPerformed
        // TODO add your handling code here:
        if (!(this.tfAdminUsername.getText().equals(""))&& !(this.tfAdminPass.getText().equals(""))) {
            this.pw.println("noviAdmin:"+tfAdminUsername.getText()+ ":"+ this.tfAdminPass.getText());
    	}
    }//GEN-LAST:event_btnDodAdminaActionPerformed

    private void cbPredmetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPredmetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPredmetiActionPerformed

    private void cbStudentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStudentiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStudentiActionPerformed

    private void btnDodNaPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodNaPredmetActionPerformed
        // TODO add your handling code here:
        if (!(this.cbStudenti.getSelectedItem()==null)&& !(this.cbPredmeti.getSelectedItem()==null)) {
            this.pw.println("dodNaPredmet:"+this.cbStudenti.getSelectedItem()+ ":"+ this.cbPredmeti.getSelectedItem());
        }
    }//GEN-LAST:event_btnDodNaPredmetActionPerformed

    private void cbPredmetiStud2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPredmetiStud2ActionPerformed
        // TODO add your handling code here:
        if (!(this.cbPredmetiStud2.getSelectedItem()==null)) {
            this.pw.println("OcenaStudent:"+this.tfUsername.getText()+":"+this.cbPredmetiStud2.getSelectedItem());
        }
    }//GEN-LAST:event_cbPredmetiStud2ActionPerformed

    private void tfOcenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOcenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOcenaActionPerformed

    private void cbPredmetiStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPredmetiStudActionPerformed
        // TODO add your handling code here:
        if (!(this.cbPredmetiStud.getSelectedItem()==null)) {
            this.pw.println("KatPredmetaKojiSlusaIndex:"+this.cbPredmetiStud.getSelectedItem());
        }
    }//GEN-LAST:event_cbPredmetiStudActionPerformed

    private void cbStudenti2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStudenti2ActionPerformed
        // TODO add your handling code here:
        if (!(this.cbStudenti2.getSelectedItem()==null)) {
            this.pw.println("predmetiKojeSlusaIndex:"+this.cbStudenti2.getSelectedItem());
        }
    }//GEN-LAST:event_cbStudenti2ActionPerformed

    private void cbKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbKatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (!(this.tfOcena.getText().equals(""))) {
            this.pw.println("Ocena:"+this.tfOcena.getText()+":"+this.cbStudenti2.getSelectedItem()+":"+this.cbPredmetiStud.getSelectedItem()+":"+this.cbKat.getSelectedItem());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbStudenti2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbStudenti2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStudenti2ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EindexKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EindexKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EindexKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EindexKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EindexKlijent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodAdmina;
    private javax.swing.JButton btnDodNaPredmet;
    private javax.swing.JButton btnDodPredmet;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnKat;
    private javax.swing.JButton btnKonekcija;
    private javax.swing.JButton btnStud;
    private javax.swing.JComboBox<String> cbKat;
    public javax.swing.JComboBox<String> cbPredmeti;
    private javax.swing.JComboBox<String> cbPredmeti2;
    public javax.swing.JComboBox<String> cbPredmetiStud;
    public javax.swing.JComboBox<String> cbPredmetiStud2;
    public javax.swing.JComboBox<String> cbStudenti;
    public javax.swing.JComboBox<String> cbStudenti2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lKonekcija;
    public javax.swing.JLabel lOcena;
    private javax.swing.JLabel lProveriBodove;
    public javax.swing.JLabel lProveriLogin;
    public javax.swing.JLabel lStudent;
    public javax.swing.JPanel pAdmin;
    public javax.swing.JPanel pLogin;
    public javax.swing.JPanel pStudent;
    private javax.swing.JPasswordField pfPass;
    public javax.swing.JTextArea taPodaciOStudentu;
    public javax.swing.JTextArea taPodaciOStudentu1;
    public javax.swing.JTextArea taPodaciOStudentu22;
    private javax.swing.JTextField tfAdminPass;
    private javax.swing.JTextField tfAdminUsername;
    public javax.swing.JTextField tfIme;
    private javax.swing.JTextField tfImeKat;
    private javax.swing.JTextField tfIndex;
    private javax.swing.JTextField tfJmbg;
    private javax.swing.JTextField tfMaxBodovi;
    private javax.swing.JTextField tfNazivPredmeta;
    private javax.swing.JTextField tfNewPassword;
    private javax.swing.JTextField tfNewUsername;
    private javax.swing.JTextField tfOcena;
    private javax.swing.JTextField tfPrezime;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
